### ISSUE TITLE
Your code failed to build on MSYS2 MINGW64

### ISSUE THREAD

**Issue by iahung** [sodium-project/salt#15]
Even though I don't know what your code does, it failed to build on MSYS2 MINGW64.

**Comment by akukh** [comment]
Hi @iahung,

Please see the discussion here: [What does this project do?](https://github.com/sodium-project/salt/issues/13)
There I described in a little more detail what this project was.

At this moment, I have not added the possibility to compile my project under MSYS2 MINGW64. This project will only be built with Clang and there are a few reasons for that. Nevertheless, I am pleasantly surprised by such interest in my little project.
